---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: brimstone
# description will be included in the image's metadata
description: best of both worlds gaming and development with Cosmic DE

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      cleanup: true
      files:
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    group-install:
      with-optional: true
      packages:
      - cosmic-desktop
      - cosmic-desktop-apps
      exclude:
        - SDL3-devel
    install:
      skip-unavailable: true
      packages:
      # All gpg subpackages to fix issues with yubikey pgp smartcard
      - gnupg2-dirmngr
      - gnupg2-g13
      - gnupg2-gpg
      - gnupg2-gpgconf
      - gnupg2-keyboxd
      - gnupg2-scdaemon
      - gnupg2-smime
      - gnupg2-utils
      - gnupg2-verify
      - gnupg2-wks
      # other helpful devy tools
      - android-tools
      - bcc
      - bpftop
      - bpftrace
      - ccache
      - flatpak-builder
      - git-subtree
      - nicstat
      - numactl
      - podman-machine
      - podman-tui
      - qemu-kvm
      - restic
      - rclone
      - sysprof
      - tiptop
      - usbmuxd
      - zsh
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.garudalinux.firedragon
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: chezmoi
    repository: "https://github.com/arades79/dotfiles" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
